// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Failure of ProcessImport is not a fatal exception.", Scope = "member", Target = "~M:Capgemini.Xrm.DataMigration.Engine.DataProcessors.MappEntityProcessor.FindReplacementValue(Capgemini.Xrm.DataMigration.DataStore.EntityWrapper,System.String)~System.Guid")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Failure of DeleteEntity is not a fatal exception.", Scope = "member", Target = "~M:Capgemini.Xrm.DataMigration.Engine.DataProcessors.SyncEntitiesProcessor.ImportCompleted")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Failure of DeleteEntity is not a fatal exception.", Scope = "member", Target = "~M:Capgemini.Xrm.DataMigration.Engine.DataProcessors.ImportCompleted")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Failure of StartPlugins is not a fatal exception.", Scope = "member", Target = "~M:Capgemini.Xrm.DataMigration.Engine.DataProcessors.WorkflowsPluginsProcessor.StartPlugins")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Failure of StartWorkflows is not a fatal exception.", Scope = "member", Target = "~M:Capgemini.Xrm.DataMigration.Engine.DataProcessors.WorkflowsPluginsProcessor.StartWorkflows")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Failure of DeactivateSdkStep is not a fatal exception.", Scope = "member", Target = "~M:Capgemini.Xrm.DataMigration.Engine.DataProcessors.WorkflowsPluginsProcessor.DeactivateSdkStep(Capgemini.Xrm.DataMigration.Model.SdkStep)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Failure of DeactivateWorkflow is not a fatal exception.", Scope = "member", Target = "~M:Capgemini.Xrm.DataMigration.Engine.DataProcessors.WorkflowsPluginsProcessor.DeactivateWorkflow(Capgemini.Xrm.DataMigration.Model.WorkflowEntity)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Reviewed", Scope = "member", Target = "~M:Capgemini.Xrm.DataMigration.Engine.DataProcessors.MapEntityProcessor.FindReplacementValue(Capgemini.Xrm.DataMigration.DataStore.EntityWrapper,System.String)~System.Guid")]