jobs: 
  - job: CommonBuildJob
    variables:
      - name: solution
        value: '**/*.sln'
      - name: buildPlatform
        value: 'Any CPU'
      - name: buildConfiguration
        value: 'Release'
    displayName: Build test and analyse
    steps:
        - task: gitversion/setup@0
          displayName: Install GitVersion
          inputs:
            versionSpec: '5.x'

        - task: gittools.gitversion.gitversion-task.GitVersion@5
          displayName: GitVersion
          inputs:
            runtime: full
            configFilePath: '$(Build.SourcesDirectory)\GitVersion.yml'
            updateAssemblyInfo: false

        - task: NuGetCommand@2
          displayName: Restore packages
          inputs:
            restoreSolution: '$(solution)'

        - task: SonarCloudPrepare@1
          displayName: Prepare SonarCloud
          inputs:
            SonarCloud: 'SonarCloud'
            organization: 'capgemini-1'
            scannerMode: 'MSBuild'
            projectKey: 'xrm-datamigration'
            projectName: 'xrm-datamigration'
            projectVersion: '$(GitVersion.NuGetVersionV2)'

        - task: VSBuild@1
          displayName: Build solution
          inputs:
            solution: '$(solution)'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'

        - task: VSTest@2
          displayName: Run tests
          inputs:
            searchFolder: tests
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
            codeCoverageEnabled: true
            testAssemblyVer2: |
             **\*Tests*.dll
             !**\*Integration*.dll
             !**\obj\**

#         - task: whitesource.ws-bolt.bolt.wss.WhiteSource Bolt@20
#           displayName: 'WhiteSource Bolt'
#           inputs:
#             cwd: '$(Build.SourcesDirectory)'

        - task: SonarCloudAnalyze@1
          displayName: 'Run Code Analysis'

        - task: SonarCloudPublish@1
          displayName: Publish SonarCloud results
          inputs:
            pollingTimeoutSec: '300'

        - task: DotNetCoreCLI@2
          displayName: Pack NuGet package
          inputs:
            command: pack
            packagesToPack: src/Capgemini.Xrm.DataMigration.Engine/Capgemini.Xrm.DataMigration.Engine.csproj
            modifyOutputPath: true 
            versioningScheme: byEnvVar
            versionEnvVar: GitVersion.NuGetVersionV2
            nobuild: true
            buildProperties: Configuration=$(buildConfiguration)
            packDirectory: '$(Build.ArtifactStagingDirectory)/package'

        - task: NuGetCommand@2
          displayName: Pack NuGet package
          inputs:
            command: custom
            arguments: pack src/Capgemini.Xrm.DataMigration.Engine/Capgemini.Xrm.DataMigration.Engine.csproj -IncludeReferencedProjects -Symbols -SymbolPackageFormat snupkg -Version $(GitVersion.NuGetVersionV2) --OutputDirectory '$(Build.ArtifactStagingDirectory)/package'

        - task: CopyFiles@2
          displayName: Copy tests to staging directory
          inputs:
            Contents: '**/$(buildConfiguration)/**'
            SourceFolder: tests
            TargetFolder: '$(Build.ArtifactStagingDirectory)/tests'

        - publish: $(Build.ArtifactStagingDirectory)/package
          displayName: Publish NuGet artifact
          artifact: Capgemini.Xrm.DataMigration.Engine

        - publish: $(Build.ArtifactStagingDirectory)/tests
          displayName: Publish tests
          artifact: Capgemini.Xrm.DataMigration.Tests
